algo_1d_btc:
  BTC_1D_API_KEY: V6Xqd53QTQuEpasf3q
  BTC_1D_SECRET_KEY: c5AS6X7VboHQWwVk8XqVfLRqR3r6Q7k999cJ

algo_1d_eth:
  ETH_1D_API_KEY: NxL049GVEsgk2WonYd
  ETH_1D_SECRET_KEY: x5M3SJyaXG759TgygyMVL02BJeyMxwQPIl1W

algo_1d_sol:
  SOL_1D_API_KEY: 4yBes0JzET4eiqWnqw
  SOL_1D_SECRET_KEY: 1HgyYlQ2e0OiorSYFopAXE077S5Zbqa7QkqZ

algo_1d_sui:
  SUI_1D_API_KEY: 2EsHL6U5BKMRzwClbE
  SUI_1D_SECRET_KEY: XzDiNN2WQ1Lx2nScaDaPl94ik7VBuGYvLuqW

algo_1d_doge:
  DOGE_1D_API_KEY: AZ0DQYiwrq1zsaq3JV
  DOGE_1D_SECRET_KEY: vHo00dAgfXcOjwCQk9iaYeYfzMGvvEcrT2b1

grassnode:
  GN_API: 2wlOd0ApVQgg4SDPqFk2Lq2Btku

tg_bot:
  TOKEN: 8641806201:AAFzzNk2TQtzbWTgBbeoXE65p5uDvjGYXeE
  GROUP_ID: 8394621040